kind = "api"
previewPath = "/"
title = "Tradey Boi X"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 5000
name = "Tradey Boi X"
paths = ["/"]

[services.development]
run = "cd tradey-boi-x && streamlit run dashboard.py"

[services.production]

[services.production.run]
args = ["bash", "tradey-boi-x/start.sh"]

[services.production.run.env]
PORT = "5000"
