kind = "api"
previewPath = "/"
title = "Tradey Boi X"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 5050
name = "Tradey Boi X"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/api-server run dev"

[services.production]

[services.production.run]
args = ["python", "main.py"]

[services.production.run.env]
PORT = "5050"
